#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'


cookbook 'runit'
cookbook 'nodejs', '~> 2.2.0'
cookbook 'mongodb', '~> 0.16.2'
cookbook 'git'